services:
  - type: web
    name: logistics-metabase
    runtime: image
    image:
      url: docker.io/metabase/metabase:v0.52.9
    plan: free
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_HOST
        fromDatabase:
          name: logistics-metabase-db
          property: host
      - key: MB_DB_PORT
        fromDatabase:
          name: logistics-metabase-db
          property: port
      - key: MB_DB_DBNAME
        fromDatabase:
          name: logistics-metabase-db
          property: database
      - key: MB_DB_USER
        fromDatabase:
          name: logistics-metabase-db
          property: user
      - key: MB_DB_PASS
        fromDatabase:
          name: logistics-metabase-db
          property: password
      - key: MB_SITE_URL
        value: https://logistics-metabase.onrender.com
    healthCheckPath: /api/health

databases:
  - name: logistics-metabase-db
    plan: free
    databaseName: metabase_app
